FROM 62.84.119.13:8123/mywebapp:v1.0 as build
FROM tomcat:7.0.92-jre8-alpine
COPY --from=build /boxfuse/boxfuse-sample-java-war-hello/target/*.war /usr/local/tomcat/webapps/
CMD ["/usr/local/tomcat/bin/catalina.sh", "run"]
